name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  RESOURCE_GROUP: my-resource-group
  FRONTEND_STORAGE_ACCOUNT: myfront123
  FRONTEND_BUILD_DIR: build # Assuming your React build outputs to a 'build' folder at the root of this repo

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to checkout code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version
          cache: 'npm'
          cache-dependency-path: 'package-lock.json' # Adjust if using yarn or different path

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend (React with Tailwind)
        run: npm run build

      - name: Upload Frontend to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ env.FRONTEND_STORAGE_ACCOUNT }} \
              --destination '$web' \
              --source ${{ env.FRONTEND_BUILD_DIR }} \
              --overwrite true
