name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Check secret availability
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}" ]; then
            echo "Secret AZURE_STATIC_WEB_APP_TOKEN is empty or missing!"
            exit 1
          else
            echo "Secret AZURE_STATIC_WEB_APP_TOKEN is present."
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APP_TOKEN }}
          app_location: "/"
          api_location: ""
          output_location: "build"
